// overlay-compat/src/components/ChatRenderer/index.vue
<template>
  <yt-live-chat-renderer class="style-scope yt-live-chat-app" style="--scrollbar-width:11px;" hide-timestamps
    @mousemove="refreshCantScrollStartTime"
  >
    <ticker class="style-scope yt-live-chat-renderer" :messages.sync="paidMessages" :showGiftName="showGiftName"></ticker>
    <yt-live-chat-item-list-renderer class="style-scope yt-live-chat-renderer" allow-scroll>
      <div ref="scroller" id="item-scroller" class="style-scope yt-live-chat-item-list-renderer animated" @scroll="onScroll">
        <div ref="itemOffset" id="item-offset" class="style-scope yt-live-chat-item-list-renderer">
          <div ref="items" id="items" class="style-scope yt-live-chat-item-list-renderer" style="overflow: hidden"
            :style="{ transform: `translateY(${Math.floor(scrollPixelsRemaining)}px)` }"
          >
            <template v-for="message in messages">
              <text-message :key="message.id" v-if="message.type === MESSAGE_TYPE_TEXT"
                class="style-scope yt-live-chat-item-list-renderer"
                :time="message.time"
                :avatarUrl="message.avatarUrl"
                :authorName="message.authorName"
                :authorType="message.authorType"
                :privilegeType="message.privilegeType"
                :contentParts="getShowContentParts(message)"
                :repeated="message.repeated"
              ></text-message>
              <paid-message :key="message.id" v-else-if="message.type === MESSAGE_TYPE_GIFT"
                class="style-scope yt-live-chat-item-list-renderer"
                :time="message.time"
                :avatarUrl="message.avatarUrl"
                :authorName="getShowAuthorName(message)"
                :price="message.price"
                :priceText="message.price <= 0 ? getGiftShowNameAndNum(message) : ''"
                :content="message.price <= 0 ? '' : getGiftShowContent(message)"
              ></paid-message>
              <membership-item :key="message.id" v-else-if="message.type === MESSAGE_TYPE_MEMBER"
                class="style-scope yt-live-chat-item-list-renderer"
                :time="message.time"
                :avatarUrl="message.avatarUrl"
                :authorName="getShowAuthorName(message)"
                :privilegeType="message.privilegeType"
                :title="message.title"
              ></membership-item>
              <paid-message :key="message.id" v-else-if="message.type === MESSAGE_TYPE_SUPER_CHAT"
                class="style-scope yt-live-chat-item-list-renderer"
                :time="message.time"
                :avatarUrl="message.avatarUrl"
                :authorName="getShowAuthorName(message)"
                :price="message.price"
                :content="getShowContent(message)"
              ></paid-message>
            </template>
          </div>
        </div>
      </div>
    </yt-live-chat-item-list-renderer>
  </yt-live-chat-renderer>
</template>

<script>
import * as chatConfig from '@/api/chatConfig'
import Ticker from './Ticker'
import TextMessage from './TextMessage'
import MembershipItem from './MembershipItem'
import PaidMessage from './PaidMessage'
import * as constants from './constants'

// 用来统计进队列时间间隔
const ENQUEUE_INTERVALS_MAX_TIME_RANGE = 3000
const ENQUEUE_INTERVALS_MAX_LENGTH = 10
// 要添加的消息类型
const ADD_MESSAGE_TYPES = [
  constants.MESSAGE_TYPE_TEXT,
  constants.MESSAGE_TYPE_GIFT,
  constants.MESSAGE_TYPE_MEMBER,
  constants.MESSAGE_TYPE_SUPER_CHAT,
]
// 发送消息时间间隔范围
const MESSAGE_MIN_INTERVAL = 80
const MESSAGE_MAX_INTERVAL = 1000

// 每次发送消息后增加的动画时间，要比MESSAGE_MIN_INTERVAL稍微大一点，太小了动画不连续，太大了发送消息时会中断动画
// 84 = ceil((1000 / 60) * 5)
const CHAT_SMOOTH_ANIMATION_TIME_MS = 84
// 滚动条距离底部小于多少像素则认为在底部
const SCROLLED_TO_BOTTOM_EPSILON = 15

export default {
  name: 'ChatRenderer',
  components: {
    Ticker,
    TextMessage,
    MembershipItem,
    PaidMessage
  },
  props: {
    maxNumber: {
      type: Number,
      default: chatConfig.DEFAULT_CONFIG.maxNumber
    },
    showGiftName: {
      type: Boolean,
      default: chatConfig.DEFAULT_CONFIG.showGiftName
    }
  },
  data() {
    return {
      MESSAGE_TYPE_TEXT: constants.MESSAGE_TYPE_TEXT,
      MESSAGE_TYPE_GIFT: constants.MESSAGE_TYPE_GIFT,
      MESSAGE_TYPE_MEMBER: constants.MESSAGE_TYPE_MEMBER,
      MESSAGE_TYPE_SUPER_CHAT: constants.MESSAGE_TYPE_SUPER_CHAT,

      messages: [],                        // 显示的消息
      paidMessages: [],                    // 固定在上方的消息

      smoothedMessageQueue: [],            // 平滑消息队列，由外部调用addMessages等方法添加
      emitSmoothedMessageTimerId: null,    // 消费平滑消息队列的定时器ID
      enqueueIntervals: [],                // 最近进队列的时间间隔，用来估计下次进队列的时间
      lastEnqueueTime: null,               // 上次进队列的时间
      estimatedEnqueueInterval: null,      // 估计的下次进队列时间间隔

      messagesBuffer: [],                  // 暂时未显示的消息，当不能自动滚动时会积压在这
      preinsertHeight: 0,                  // 插入新消息之前items的高度
      isSmoothed: true,                    // 是否平滑滚动，当消息太快时不平滑滚动
      chatRateMs: 1000,                    // 用来计算消息速度
      scrollPixelsRemaining: 0,            // 平滑滚动剩余像素
      scrollTimeRemainingMs: 0,            // 平滑滚动剩余时间
      lastSmoothChatMessageAddMs: null,    // 上次showNewMessages时间
      smoothScrollRafHandle: null,         // 平滑滚动requestAnimationFrame句柄
      lastSmoothScrollUpdate: null,        // 平滑滚动上一帧时间

      atBottom: true,                      // 滚动到底部，用来判断能否自动滚动
      cantScrollStartTime: null            // 开始不能自动滚动的时间，用来防止卡住
    }
  },
  computed: {
    canScrollToBottom() {
      return this.atBottom/* || this.allowScroll */
    }
  },
  watch: {
    canScrollToBottom(val) {
      this.cantScrollStartTime = val ? null : new Date()
    }
  },
  mounted() {
    this.scrollToBottom()
  },
  beforeDestroy() {
    if (this.emitSmoothedMessageTimerId) {
      window.clearTimeout(this.emitSmoothedMessageTimerId)
      this.emitSmoothedMessageTimerId = null
    }
    this.clearMessages()
  },
  methods: {
    getGiftShowContent(message) {
      return constants.getGiftShowContent(message, this.showGiftName)
    },
    getGiftShowNameAndNum: constants.getGiftShowNameAndNum,
    getShowContent: constants.getShowContent,
    getShowContentParts: constants.getShowContentParts,
    getShowAuthorName: constants.getShowAuthorName,

    addMessage(message) {
      this.addMessages([message])
    },
    addMessages(messages) {
      this.enqueueMessages(messages)
    },
    // 后悔加这个功能了
    mergeSimilarText(content) {
      content = content.trim().toLowerCase()
      for (let message of this.iterRecentMessages(5)) {
        if (message.type !== constants.MESSAGE_TYPE_TEXT) {
          continue
        }

        let messageContent = message.content.trim().toLowerCase()
        let longer, shorter
        if (messageContent.length > content.length) {
          longer = messageContent
          shorter = content
        } else {
          longer = content
          shorter = messageContent
        }

        if (
          longer.indexOf(shorter) !== -1 // 长的包含短的
          && longer.length - shorter.length < shorter.length // 长度差较小
        ) {
          this.updateMessage(message.id, { $add: {
            repeated: 1
          } })
          return true
        }
      }
      return false
    },
    mergeSimilarGift(authorName, price, _totalFreeCoin, giftName, num) {
      for (let message of this.iterRecentMessages(5)) {
        if (
          message.type === constants.MESSAGE_TYPE_GIFT
          && message.authorName === authorName
          && message.giftName === giftName
        ) {
          this.updateMessage(message.id, { $add: {
            price: price,
            // totalFreeCoin: totalFreeCoin, // 暂时没用到
            num: num
          } })
          return true
        }
      }
      return false
    },
    // 从新到老迭代num条消息，注意会迭代smoothedMessageQueue，不会迭代paidMessages
    *iterRecentMessages(num, onlyCountAddMessages = true) {
      if (num <= 0) {
        return
      }
      for (let arr of this.iterMessageArrs()) {
        for (let i = arr.length - 1; i >= 0 && num > 0; i--) {
          let message = arr[i]
          yield message
          if (!onlyCountAddMessages || this.isAddMessage(message)) {
            num--
          }
        }
        if (num <= 0) {
          break
        }
      }
    },
    // 从新到老迭代消息的数组
    *iterMessageArrs() {
      for (let i = this.smoothedMessageQueue.length - 1; i >= 0; i--) {
        yield this.smoothedMessageQueue[i]
      }
      yield this.messagesBuffer
      yield this.messages
    },
    delMessage(id) {
      this.delMessages([id])
    },
    delMessages(ids) {
      this.enqueueMessages(ids.map(
        id => ({
          type: constants.MESSAGE_TYPE_DEL,
          id
        })
      ))
    },
    clearMessages() {
      this.messages = []
      this.paidMessages = []
      this.smoothedMessageQueue = []
      this.messagesBuffer = []
      this.isSmoothed = true
      this.lastSmoothChatMessageAddMs = null
      this.chatRateMs = 1000
      this.lastSmoothScrollUpdate = null
      this.scrollTimeRemainingMs = this.scrollPixelsRemaining = 0
      this.smoothScrollRafHandle = null
      this.preinsertHeight = 0
      this.maybeResizeScrollContainer()
      if (!this.atBottom) {
        this.scrollToBottom()
      }
    },
    updateMessage(id, newValuesObj) {
      this.enqueueMessages([{
        type: constants.MESSAGE_TYPE_UPDATE,
        id,
        newValuesObj
      }])
    },

    enqueueMessages(messages) {
      // 估计进队列时间间隔
      if (!this.lastEnqueueTime) {
        this.lastEnqueueTime = new Date()
      } else {
        let curTime = new Date()
        let interval = curTime - this.lastEnqueueTime
        this.enqueueIntervals.push(interval)

        // 统计最近ENQUEUE_INTERVALS_MAX_TIME_RANGE内的间隔，最多ENQUEUE_INTERVALS_MAX_LENGTH个
        let keepFrom = this.enqueueIntervals.length - 1
        let minKeepFrom = Math.max(this.enqueueIntervals.length - ENQUEUE_INTERVALS_MAX_LENGTH, 0)
        let prevIdxPassedTime = 0
        for (; keepFrom > minKeepFrom; keepFrom--) {
          let itInterval = this.enqueueIntervals[keepFrom]
          prevIdxPassedTime += itInterval
          if (prevIdxPassedTime > ENQUEUE_INTERVALS_MAX_TIME_RANGE) {
            break
          }
        }
        if (keepFrom > 0) {
          this.enqueueIntervals.splice(0, keepFrom)
        }

        // 这边估计得尽量大，只要不太早把消息缓冲发完就是平滑的。有MESSAGE_MAX_INTERVAL保底，不会让消息延迟太大
        let maxEnqueueInterval = this.enqueueIntervals[0]
        for (let interval_ of this.enqueueIntervals) {
          if (interval_ > maxEnqueueInterval) {
            maxEnqueueInterval = interval_
          }
        }
        this.estimatedEnqueueInterval = maxEnqueueInterval
        this.lastEnqueueTime = curTime
      }

      // 把messages分成messageGroup，每个组里最多有1个需要平滑的消息
      let messageGroup = []
      for (let message of messages) {
        messageGroup.push(message)
        if (this.isAddMessage(message)) {
          this.smoothedMessageQueue.push(messageGroup)
          messageGroup = []
        }
      }
      // 还剩下不需要平滑的消息
      if (messageGroup.length > 0) {
        if (this.smoothedMessageQueue.length > 0) {
          // 和上一组合并
          let lastMessageGroup = this.smoothedMessageQueue[this.smoothedMessageQueue.length - 1]
          for (let message of messageGroup) {
            lastMessageGroup.push(message)
          }
        } else {
          // 自己一个组
          this.smoothedMessageQueue.push(messageGroup)
        }
      }

      if (!this.emitSmoothedMessageTimerId) {
        this.emitSmoothedMessageTimerId = window.setTimeout(this.emitSmoothedMessages)
      }
    },
    isAddMessage({ type }) {
      return ADD_MESSAGE_TYPES.indexOf(type) !== -1
    },
    emitSmoothedMessages() {
      this.emitSmoothedMessageTimerId = null
      if (this.smoothedMessageQueue.length <= 0) {
        return
      }

      // 估计的下次进队列剩余时间
      let estimatedNextEnqueueRemainTime = 10 * 1000
      if (this.estimatedEnqueueInterval) {
        estimatedNextEnqueueRemainTime = Math.max(this.lastEnqueueTime - new Date() + this.estimatedEnqueueInterval, 1)
      }
      // 计算发送的消息数，保证在下次进队列之前发完
      // 下次进队列之前应该发多少条消息
      let shouldEmitGroupNum = Math.max(this.smoothedMessageQueue.length, 0)
      // 下次进队列之前最多能发多少次
      let maxCanEmitCount = estimatedNextEnqueueRemainTime / MESSAGE_MIN_INTERVAL
      // 这次发多少条消息
      let groupNumToEmit
      if (shouldEmitGroupNum < maxCanEmitCount) {
        // 队列中消息数很少，每次发1条也能发完
        groupNumToEmit = 1
      } else {
        // 每次发1条以上，保证按最快速度能发完
        groupNumToEmit = Math.ceil(shouldEmitGroupNum / maxCanEmitCount)
      }

      // 发消息
      let messageGroups = this.smoothedMessageQueue.splice(0, groupNumToEmit)
      let mergedGroup = []
      for (let messageGroup of messageGroups) {
        for (let message of messageGroup) {
          mergedGroup.push(message)
        }
      }
      this.handleMessageGroup(mergedGroup)

      if (this.smoothedMessageQueue.length <= 0) {
        return
      }
      // 消息没发完，计算下次发消息时间
      let sleepTime
      if (groupNumToEmit === 1) {
        // 队列中消息数很少，随便定个[MESSAGE_MIN_INTERVAL, MESSAGE_MAX_INTERVAL]的时间
        sleepTime = estimatedNextEnqueueRemainTime / this.smoothedMessageQueue.length
        sleepTime *= 0.5 + Math.random()
        if (sleepTime > MESSAGE_MAX_INTERVAL) {
          sleepTime = MESSAGE_MAX_INTERVAL
        } else if (sleepTime < MESSAGE_MIN_INTERVAL) {
          sleepTime = MESSAGE_MIN_INTERVAL
        }
      } else {
        // 按最快速度发
        sleepTime = MESSAGE_MIN_INTERVAL
      }
      this.emitSmoothedMessageTimerId = window.setTimeout(this.emitSmoothedMessages, sleepTime)
    },

    handleMessageGroup(messageGroup) {
      if (messageGroup.length <= 0) {
        return
      }

      for (let message of messageGroup) {
        switch (message.type) {
        case constants.MESSAGE_TYPE_TEXT:
        case constants.MESSAGE_TYPE_GIFT:
        case constants.MESSAGE_TYPE_MEMBER:
        case constants.MESSAGE_TYPE_SUPER_CHAT:
          // 这里处理的类型要和 ADD_MESSAGE_TYPES 一致
          this.handleAddMessage(message)
          break
        case constants.MESSAGE_TYPE_DEL:
          this.handleDelMessage(message)
          break
        case constants.MESSAGE_TYPE_UPDATE:
          this.handleUpdateMessage(message)
          break
        }
      }

      this.maybeResizeScrollContainer()
      this.flushMessagesBuffer()
      this.$nextTick(this.maybeScrollToBottom)
    },
    handleAddMessage(message) {
      // 添加一个本地时间给Ticker用，防止本地时间和服务器时间相差很大的情况
      message.addTime = new Date()

      if (message.type !== constants.MESSAGE_TYPE_TEXT) {
        this.paidMessages.unshift(JSON.parse(JSON.stringify(message)))
        const MAX_PAID_MESSAGE_NUM = 100
        if (this.paidMessages.length > MAX_PAID_MESSAGE_NUM) {
          this.paidMessages.splice(MAX_PAID_MESSAGE_NUM, this.paidMessages.length - MAX_PAID_MESSAGE_NUM)
        }
      }

      // 不知道cloneDeep拷贝Vue的响应式对象会不会有问题，保险起见把这句放在后面
      this.messagesBuffer.push(message)
    },
    handleDelMessage({ id }) {
      let arrs = [this.messages, this.paidMessages, this.messagesBuffer]
      let needResetSmoothScroll = false
      for (let arr of arrs) {
        for (let i = 0; i < arr.length; i++) {
          if (arr[i].id !== id) {
            continue
          }
          arr.splice(i, 1)
          if (arr === this.messages) {
            needResetSmoothScroll = true
          }
          break
        }
      }
      if (needResetSmoothScroll) {
        this.resetSmoothScroll()
      }
    },
    handleUpdateMessage({ id, newValuesObj }) {
      let arrs = [this.messages, this.paidMessages, this.messagesBuffer]
      let needResetSmoothScroll = false
      for (let arr of arrs) {
        for (let message of arr) {
          if (message.id !== id) {
            continue
          }
          this.doUpdateMessage(message, newValuesObj)
          if (arr === this.messages) {
            needResetSmoothScroll = true
          }
          break
        }
      }
      if (needResetSmoothScroll) {
        this.resetSmoothScroll()
      }
    },
    doUpdateMessage(message, newValuesObj) {
      // +=
      let addValuesObj = newValuesObj.$add
      if (addValuesObj !== undefined) {
        for (let name in addValuesObj) {
          message[name] += addValuesObj[name]
        }
      }

      // =
      for (let name in newValuesObj) {
        if (!name.startsWith('$')) {
          message[name] = newValuesObj[name]
        }
      }
    },

    async flushMessagesBuffer() {
      if (this.messagesBuffer.length <= 0) {
        return
      }
      if (!this.canScrollToBottomOrTimedOut()) {
        if (this.messagesBuffer.length > this.maxNumber) {
          // 未显示消息数 > 最大可显示数，丢弃
          this.messagesBuffer.splice(0, this.messagesBuffer.length - this.maxNumber)
        }
        return
      }

      let removeNum = Math.max(this.messages.length + this.messagesBuffer.length - this.maxNumber, 0)
      if (removeNum > 0) {
        this.messages.splice(0, removeNum)
        // 防止同时添加和删除项目时所有的项目重新渲染 https://github.com/vuejs/vue/issues/6857
        await this.$nextTick()
      }

      this.preinsertHeight = this.$refs.items.clientHeight
      for (let message of this.messagesBuffer) {
        this.messages.push(message)
      }
      this.messagesBuffer = []
      // 等items高度变化
      await this.$nextTick()
      this.showNewMessages()
    },
    showNewMessages() {
      let hasScrollBar = this.$refs.items.clientHeight > this.$refs.scroller.clientHeight
      this.$refs.itemOffset.style.height = `${this.$refs.items.clientHeight}px`
      if (!this.canScrollToBottomOrTimedOut() || !hasScrollBar) {
        return
      }

      // 计算剩余像素
      this.scrollPixelsRemaining += this.$refs.items.clientHeight - this.preinsertHeight
      this.scrollToBottom()

      // 计算是否平滑滚动、剩余时间
      if (!this.lastSmoothChatMessageAddMs) {
        this.lastSmoothChatMessageAddMs = performance.now()
      }
      let interval = performance.now() - this.lastSmoothChatMessageAddMs
      this.chatRateMs = (0.9 * this.chatRateMs) + (0.1 * interval)
      if (this.isSmoothed) {
        if (this.chatRateMs < 400) {
          this.isSmoothed = false
        }
      } else {
        if (this.chatRateMs > 450) {
          this.isSmoothed = true
        }
      }
      this.scrollTimeRemainingMs += this.isSmoothed ? CHAT_SMOOTH_ANIMATION_TIME_MS : 0

      if (!this.smoothScrollRafHandle) {
        this.smoothScrollRafHandle = window.requestAnimationFrame(this.smoothScroll)
      }
      this.lastSmoothChatMessageAddMs = performance.now()
    },
    smoothScroll(time) {
      if (!this.lastSmoothScrollUpdate) {
        // 第一帧
        this.lastSmoothScrollUpdate = time
        this.smoothScrollRafHandle = window.requestAnimationFrame(this.smoothScroll)
        return
      }

      let interval = time - this.lastSmoothScrollUpdate
      if (
        this.scrollPixelsRemaining <= 0 || this.scrollPixelsRemaining >= 400  // 已经滚动到底部或者离底部太远则结束
        || interval >= 1000 // 离上一帧时间太久，可能用户切换到其他网页
        || this.scrollTimeRemainingMs <= 0 // 时间已结束
      ) {
        this.resetSmoothScroll()
        return
      }

      let pixelsToScroll = interval / this.scrollTimeRemainingMs * this.scrollPixelsRemaining
      this.scrollPixelsRemaining -= pixelsToScroll
      if (this.scrollPixelsRemaining < 0) {
        this.scrollPixelsRemaining = 0
      }
      this.scrollTimeRemainingMs -= interval
      if (this.scrollTimeRemainingMs < 0) {
        this.scrollTimeRemainingMs = 0
      }
      this.lastSmoothScrollUpdate = time
      this.smoothScrollRafHandle = window.requestAnimationFrame(this.smoothScroll)
    },
    resetSmoothScroll() {
      this.scrollTimeRemainingMs = this.scrollPixelsRemaining = 0
      this.lastSmoothScrollUpdate = null
      if (this.smoothScrollRafHandle) {
        window.cancelAnimationFrame(this.smoothScrollRafHandle)
        this.smoothScrollRafHandle = null
      }
    },

    maybeResizeScrollContainer() {
      this.$refs.itemOffset.style.height = `${this.$refs.items.clientHeight}px`
      this.$refs.itemOffset.style.minHeight = `${this.$refs.scroller.clientHeight}px`
      this.maybeScrollToBottom()
    },
    maybeScrollToBottom() {
      if (this.canScrollToBottomOrTimedOut()) {
        this.scrollToBottom()
      }
    },
    scrollToBottom() {
      this.$refs.scroller.scrollTop = Math.pow(2, 24)
      this.atBottom = true
    },
    onScroll() {
      this.refreshCantScrollStartTime()
      let scroller = this.$refs.scroller
      this.atBottom = scroller.scrollHeight - scroller.scrollTop - scroller.clientHeight < SCROLLED_TO_BOTTOM_EPSILON
      this.flushMessagesBuffer()
    },
    canScrollToBottomOrTimedOut() {
      if (this.canScrollToBottom) {
        return true
      }
      // 防止在OBS中卡住，超过一定时间也可以自动滚动
      return new Date() - this.cantScrollStartTime >= 5 * 1000
    },
    refreshCantScrollStartTime() {
      // 有鼠标事件时刷新，防止用户看弹幕时自动滚动
      if (this.cantScrollStartTime) {
        this.cantScrollStartTime = new Date()
      }
    }
  }
}
</script>

<style src="@/assets/css/youtube/yt-html.css"></style>
<style src="@/assets/css/youtube/yt-live-chat-renderer.css"></style>
<style src="@/assets/css/youtube/yt-live-chat-item-list-renderer.css"></style>

// src/overlay-compat/components/ChatRenderer/index.tsx
import React, {
  forwardRef,
  useImperativeHandle,
  useState,
  useRef,
  useEffect,
} from "react";
import { flushSync } from "react-dom";
import Ticker from "./Ticker";
import TextMessage from "./TextMessage";
import MembershipItem from "./MembershipItem";
import PaidMessage from "./PaidMessage";
import * as constants from "./constants";
import * as chatConfig from "../../api/chatConfig";
import "../../assets/css/youtube/yt-html.css";
import "../../assets/css/youtube/yt-live-chat-renderer.css";
import "../../assets/css/youtube/yt-live-chat-item-list-renderer.css";

const ENQUEUE_INTERVALS_MAX_TIME_RANGE = 3000;
const ENQUEUE_INTERVALS_MAX_LENGTH = 10;
const ADD_MESSAGE_TYPES = [
  constants.MESSAGE_TYPE_TEXT,
  constants.MESSAGE_TYPE_GIFT,
  constants.MESSAGE_TYPE_MEMBER,
  constants.MESSAGE_TYPE_SUPER_CHAT,
];
const MESSAGE_MIN_INTERVAL = 80;
const MESSAGE_MAX_INTERVAL = 1000;
const CHAT_SMOOTH_ANIMATION_TIME_MS = 84;
const SCROLLED_TO_BOTTOM_EPSILON = 15;

export interface ChatRendererRef {
  addMessage: (message: any) => void;
  delMessages: (ids: string[]) => void;
  updateMessage: (id: string, newValuesObj: any) => void;
  mergeSimilarText: (content: string) => boolean;
  mergeSimilarGift: (
    authorName: string,
    price: number,
    freePrice: number,
    giftName: string,
    num: number
  ) => boolean;
  clearMessages: () => void;
}

interface ChatRendererProps {
  maxNumber?: number;
  showGiftName?: boolean;
}

export const ChatRenderer = forwardRef<ChatRendererRef, ChatRendererProps>(
  (
    {
      maxNumber = chatConfig.DEFAULT_CONFIG.maxNumber,
      showGiftName = chatConfig.DEFAULT_CONFIG.showGiftName,
    },
    ref
  ) => {
    const [messages, setMessages] = useState<any[]>([]);
    const [paidMessages, setPaidMessages] = useState<any[]>([]);

    // Mutable refs for state variables that don't directly trigger render cycles
    const smoothedMessageQueue = useRef<any[]>([]);
    const emitSmoothedMessageTimerId = useRef<any>(null);
    const enqueueIntervals = useRef<number[]>([]);
    const lastEnqueueTime = useRef<Date | null>(null);
    const estimatedEnqueueInterval = useRef<number | null>(null);

    const messagesBuffer = useRef<any[]>([]);
    const preinsertHeight = useRef<number>(0);
    const isSmoothed = useRef<boolean>(true);
    const chatRateMs = useRef<number>(1000);
    const scrollPixelsRemaining = useRef<number>(0);
    const scrollTimeRemainingMs = useRef<number>(0);
    const lastSmoothChatMessageAddMs = useRef<number | null>(null);
    const smoothScrollRafHandle = useRef<number | null>(null);
    const lastSmoothScrollUpdate = useRef<number | null>(null);

    const atBottom = useRef<boolean>(true);
    const cantScrollStartTime = useRef<Date | null>(null);

    const scrollerRef = useRef<HTMLDivElement>(null);
    const itemOffsetRef = useRef<HTMLDivElement>(null);
    const itemsRef = useRef<HTMLDivElement>(null);

    const canScrollToBottom = () => atBottom.current;

    const canScrollToBottomOrTimedOut = () => {
      if (canScrollToBottom()) {
        return true;
      }
      if (cantScrollStartTime.current === null) {
        return true;
      }
      return new Date().getTime() - cantScrollStartTime.current.getTime() >= 5 * 1000;
    };

    const refreshCantScrollStartTime = () => {
      if (cantScrollStartTime.current) {
        cantScrollStartTime.current = new Date();
      }
    };

    const scrollToBottom = () => {
      const scroller = scrollerRef.current;
      if (scroller) {
        scroller.scrollTop = Math.pow(2, 24);
      }
      atBottom.current = true;
    };

    const maybeScrollToBottom = () => {
      if (canScrollToBottomOrTimedOut()) {
        scrollToBottom();
      }
    };

    const maybeResizeScrollContainer = () => {
      const itemOffset = itemOffsetRef.current;
      const items = itemsRef.current;
      const scroller = scrollerRef.current;
      if (itemOffset && items && scroller) {
        itemOffset.style.height = `${items.clientHeight}px`;
        itemOffset.style.minHeight = `${scroller.clientHeight}px`;
      }
      maybeScrollToBottom();
    };

    const resetSmoothScroll = () => {
      scrollTimeRemainingMs.current = scrollPixelsRemaining.current = 0;
      lastSmoothScrollUpdate.current = null;
      if (smoothScrollRafHandle.current) {
        window.cancelAnimationFrame(smoothScrollRafHandle.current);
        smoothScrollRafHandle.current = null;
      }
    };

    const smoothScroll = (time: number) => {
      if (!lastSmoothScrollUpdate.current) {
        lastSmoothScrollUpdate.current = time;
        smoothScrollRafHandle.current = window.requestAnimationFrame(smoothScroll);
        return;
      }

      const interval = time - lastSmoothScrollUpdate.current;
      if (
        scrollPixelsRemaining.current <= 0 ||
        scrollPixelsRemaining.current >= 400 ||
        interval >= 1000 ||
        scrollTimeRemainingMs.current <= 0
      ) {
        resetSmoothScroll();
        return;
      }

      const pixelsToScroll =
        (interval / scrollTimeRemainingMs.current) * scrollPixelsRemaining.current;
      scrollPixelsRemaining.current -= pixelsToScroll;
      if (scrollPixelsRemaining.current < 0) {
        scrollPixelsRemaining.current = 0;
      }
      scrollTimeRemainingMs.current -= interval;
      if (scrollTimeRemainingMs.current < 0) {
        scrollTimeRemainingMs.current = 0;
      }

      if (itemsRef.current) {
        itemsRef.current.style.transform = `translateY(${Math.floor(
          scrollPixelsRemaining.current
        )}px)`;
      }

      lastSmoothScrollUpdate.current = time;
      smoothScrollRafHandle.current = window.requestAnimationFrame(smoothScroll);
    };

    const showNewMessages = () => {
      const items = itemsRef.current;
      const scroller = scrollerRef.current;
      const itemOffset = itemOffsetRef.current;
      if (!items || !scroller || !itemOffset) return;

      const hasScrollBar = items.clientHeight > scroller.clientHeight;
      itemOffset.style.height = `${items.clientHeight}px`;
      if (!canScrollToBottomOrTimedOut() || !hasScrollBar) {
        return;
      }

      // Calculate remaining pixels
      scrollPixelsRemaining.current += items.clientHeight - preinsertHeight.current;
      scrollToBottom();

      // Smooth scroll animation
      const now = performance.now();
      if (!lastSmoothChatMessageAddMs.current) {
        lastSmoothChatMessageAddMs.current = now;
      }
      const interval = now - lastSmoothChatMessageAddMs.current;
      chatRateMs.current = 0.9 * chatRateMs.current + 0.1 * interval;

      if (isSmoothed.current) {
        if (chatRateMs.current < 400) {
          isSmoothed.current = false;
        }
      } else {
        if (chatRateMs.current > 450) {
          isSmoothed.current = true;
        }
      }
      scrollTimeRemainingMs.current += isSmoothed.current ? CHAT_SMOOTH_ANIMATION_TIME_MS : 0;

      if (!smoothScrollRafHandle.current) {
        smoothScrollRafHandle.current = window.requestAnimationFrame(smoothScroll);
      }
      lastSmoothChatMessageAddMs.current = performance.now();
    };

    const flushMessagesBuffer = () => {
      if (messagesBuffer.current.length <= 0) {
        return;
      }

      if (!canScrollToBottomOrTimedOut()) {
        if (messagesBuffer.current.length > maxNumber) {
          messagesBuffer.current.splice(
            0,
            messagesBuffer.current.length - maxNumber
          );
        }
        return;
      }

      const items = itemsRef.current;
      const scroller = scrollerRef.current;
      if (!items || !scroller) return;

      flushSync(() => {
        setMessages((prevMessages) => {
          const totalLength = prevMessages.length + messagesBuffer.current.length;
          const removeNum = Math.max(totalLength - maxNumber, 0);
          const sliced = removeNum > 0 ? prevMessages.slice(removeNum) : prevMessages;
          const updated = [...sliced, ...messagesBuffer.current];
          messagesBuffer.current = [];
          return updated;
        });
      });

      preinsertHeight.current = items.clientHeight;
      // Wait for heights to update and trigger new message animations
      setTimeout(() => {
        showNewMessages();
      }, 0);
    };

    const handleAddMessage = (message: any) => {
      message.addTime = new Date();

      if (message.type !== constants.MESSAGE_TYPE_TEXT) {
        setPaidMessages((prev) => {
          const updated = [JSON.parse(JSON.stringify(message)), ...prev];
          const MAX_PAID_MESSAGE_NUM = 100;
          if (updated.length > MAX_PAID_MESSAGE_NUM) {
            updated.splice(
              MAX_PAID_MESSAGE_NUM,
              updated.length - MAX_PAID_MESSAGE_NUM
            );
          }
          return updated;
        });
      }

      messagesBuffer.current.push(message);
    };

    const handleDelMessage = ({ id }: { id: string }) => {
      let needResetSmoothScroll = false;

      // Clean local buffer
      const bufIdx = messagesBuffer.current.findIndex((m) => m.id === id);
      if (bufIdx !== -1) {
        messagesBuffer.current.splice(bufIdx, 1);
      }

      // Delete from paid messages
      setPaidMessages((prev) => prev.filter((m) => m.id !== id));

      // Delete from active messages
      flushSync(() => {
        setMessages((prev) => {
          const index = prev.findIndex((m) => m.id === id);
          if (index !== -1) {
            needResetSmoothScroll = true;
            return prev.filter((m) => m.id !== id);
          }
          return prev;
        });
      });

      if (needResetSmoothScroll) {
        resetSmoothScroll();
      }
    };

    const doUpdateMessage = (message: any, newValuesObj: any) => {
      const addValuesObj = newValuesObj.$add;
      if (addValuesObj !== undefined) {
        for (const name in addValuesObj) {
          message[name] = (message[name] || 0) + addValuesObj[name];
        }
      }

      for (const name in newValuesObj) {
        if (!name.startsWith("$")) {
          message[name] = newValuesObj[name];
        }
      }
    };

    const handleUpdateMessage = ({ id, newValuesObj }: { id: string; newValuesObj: any }) => {
      let needResetSmoothScroll = false;

      // Update buffer
      for (const message of messagesBuffer.current) {
        if (message.id === id) {
          doUpdateMessage(message, newValuesObj);
          break;
        }
      }

      // Update paid messages
      setPaidMessages((prev) =>
        prev.map((message) => {
          if (message.id === id) {
            const copy = JSON.parse(JSON.stringify(message));
            doUpdateMessage(copy, newValuesObj);
            return copy;
          }
          return message;
        })
      );

      // Update active messages
      flushSync(() => {
        setMessages((prev) =>
          prev.map((message) => {
            if (message.id === id) {
              needResetSmoothScroll = true;
              const copy = { ...message };
              doUpdateMessage(copy, newValuesObj);
              return copy;
            }
            return message;
          })
        );
      });

      if (needResetSmoothScroll) {
        resetSmoothScroll();
      }
    };

    const handleMessageGroup = (messageGroup: any[]) => {
      if (messageGroup.length <= 0) {
        return;
      }

      for (const message of messageGroup) {
        switch (message.type) {
          case constants.MESSAGE_TYPE_TEXT:
          case constants.MESSAGE_TYPE_GIFT:
          case constants.MESSAGE_TYPE_MEMBER:
          case constants.MESSAGE_TYPE_SUPER_CHAT:
            handleAddMessage(message);
            break;
          case constants.MESSAGE_TYPE_DEL:
            handleDelMessage(message);
            break;
          case constants.MESSAGE_TYPE_UPDATE:
            handleUpdateMessage(message);
            break;
        }
      }

      maybeResizeScrollContainer();
      flushMessagesBuffer();
      setTimeout(maybeScrollToBottom, 0);
    };

    const emitSmoothedMessages = () => {
      emitSmoothedMessageTimerId.current = null;
      if (smoothedMessageQueue.current.length <= 0) {
        return;
      }

      let estimatedNextEnqueueRemainTime = 10 * 1000;
      if (estimatedEnqueueInterval.current && lastEnqueueTime.current) {
        estimatedNextEnqueueRemainTime = Math.max(
          lastEnqueueTime.current.getTime() -
            new Date().getTime() +
            estimatedEnqueueInterval.current,
          1
        );
      }

      const shouldEmitGroupNum = Math.max(smoothedMessageQueue.current.length, 0);
      const maxCanEmitCount = estimatedNextEnqueueRemainTime / MESSAGE_MIN_INTERVAL;
      let groupNumToEmit: number;

      if (shouldEmitGroupNum < maxCanEmitCount) {
        groupNumToEmit = 1;
      } else {
        groupNumToEmit = Math.ceil(shouldEmitGroupNum / maxCanEmitCount);
      }

      const messageGroups = smoothedMessageQueue.current.splice(0, groupNumToEmit);
      const mergedGroup: any[] = [];
      for (const messageGroup of messageGroups) {
        for (const message of messageGroup) {
          mergedGroup.push(message);
        }
      }
      handleMessageGroup(mergedGroup);

      if (smoothedMessageQueue.current.length <= 0) {
        return;
      }

      let sleepTime: number;
      if (groupNumToEmit === 1) {
        sleepTime = estimatedNextEnqueueRemainTime / smoothedMessageQueue.current.length;
        sleepTime *= 0.5 + Math.random();
        if (sleepTime > MESSAGE_MAX_INTERVAL) {
          sleepTime = MESSAGE_MAX_INTERVAL;
        } else if (sleepTime < MESSAGE_MIN_INTERVAL) {
          sleepTime = MESSAGE_MIN_INTERVAL;
        }
      } else {
        sleepTime = MESSAGE_MIN_INTERVAL;
      }
      emitSmoothedMessageTimerId.current = window.setTimeout(
        emitSmoothedMessages,
        sleepTime
      );
    };

    const isAddMessage = ({ type }: { type: number }) => {
      return ADD_MESSAGE_TYPES.indexOf(type) !== -1;
    };

    const enqueueMessages = (incomingMessages: any[]) => {
      const curTime = new Date();
      if (!lastEnqueueTime.current) {
        lastEnqueueTime.current = curTime;
      } else {
        const interval = curTime.getTime() - lastEnqueueTime.current.getTime();
        enqueueIntervals.current.push(interval);

        let keepFrom = enqueueIntervals.current.length - 1;
        const minKeepFrom = Math.max(
          enqueueIntervals.current.length - ENQUEUE_INTERVALS_MAX_LENGTH,
          0
        );
        let prevIdxPassedTime = 0;
        for (; keepFrom > minKeepFrom; keepFrom--) {
          const itInterval = enqueueIntervals.current[keepFrom];
          prevIdxPassedTime += itInterval;
          if (prevIdxPassedTime > ENQUEUE_INTERVALS_MAX_TIME_RANGE) {
            break;
          }
        }
        if (keepFrom > 0) {
          enqueueIntervals.current.splice(0, keepFrom);
        }

        let maxEnqueueInterval = enqueueIntervals.current[0];
        for (const interval_ of enqueueIntervals.current) {
          if (interval_ > maxEnqueueInterval) {
            maxEnqueueInterval = interval_;
          }
        }
        estimatedEnqueueInterval.current = maxEnqueueInterval;
        lastEnqueueTime.current = curTime;
      }

      let messageGroup: any[] = [];
      for (const message of incomingMessages) {
        messageGroup.push(message);
        if (isAddMessage(message)) {
          smoothedMessageQueue.current.push(messageGroup);
          messageGroup = [];
        }
      }
      if (messageGroup.length > 0) {
        if (smoothedMessageQueue.current.length > 0) {
          const lastGroup =
            smoothedMessageQueue.current[smoothedMessageQueue.current.length - 1];
          for (const message of messageGroup) {
            lastGroup.push(message);
          }
        } else {
          smoothedMessageQueue.current.push(messageGroup);
        }
      }

      if (!emitSmoothedMessageTimerId.current) {
        emitSmoothedMessageTimerId.current = window.setTimeout(emitSmoothedMessages, 0);
      }
    };

    const iterRecentMessages = (num: number, onlyCountAddMessages = true) => {
      const result: any[] = [];
      if (num <= 0) return result;

      const arrays = [smoothedMessageQueue.current, messagesBuffer.current, messages];
      for (let arrIdx = arrays.length - 1; arrIdx >= 0; arrIdx--) {
        const arr = arrays[arrIdx];
        for (let i = arr.length - 1; i >= 0 && num > 0; i--) {
          const message = arrIdx === 0 ? arr[i][0] : arr[i]; // smoothedMessageQueue is double array
          if (message) {
            result.push(message);
            if (!onlyCountAddMessages || isAddMessage(message)) {
              num--;
            }
          }
        }
        if (num <= 0) break;
      }
      return result;
    };

    useImperativeHandle(ref, () => ({
      addMessage(message: any) {
        enqueueMessages([message]);
      },
      delMessages(ids: string[]) {
        enqueueMessages(
          ids.map((id) => ({
            type: constants.MESSAGE_TYPE_DEL,
            id,
          }))
        );
      },
      updateMessage(id: string, newValuesObj: any) {
        enqueueMessages([
          {
            type: constants.MESSAGE_TYPE_UPDATE,
            id,
            newValuesObj,
          },
        ]);
      },
      mergeSimilarText(content: string) {
        const trimmed = content.trim().toLowerCase();
        const recent = iterRecentMessages(5);
        for (const message of recent) {
          if (message.type !== constants.MESSAGE_TYPE_TEXT) {
            continue;
          }

          const messageContent = message.content.trim().toLowerCase();
          let longer: string, shorter: string;
          if (messageContent.length > trimmed.length) {
            longer = messageContent;
            shorter = trimmed;
          } else {
            longer = trimmed;
            shorter = messageContent;
          }

          if (
            longer.indexOf(shorter) !== -1 &&
            longer.length - shorter.length < shorter.length
          ) {
            enqueueMessages([
              {
                type: constants.MESSAGE_TYPE_UPDATE,
                id: message.id,
                newValuesObj: { $add: { repeated: 1 } },
              },
            ]);
            return true;
          }
        }
        return false;
      },
      mergeSimilarGift(
        authorName: string,
        price: number,
        _freePrice: number,
        giftName: string,
        num: number
      ) {
        const recent = iterRecentMessages(5);
        for (const message of recent) {
          if (
            message.type === constants.MESSAGE_TYPE_GIFT &&
            message.authorName === authorName &&
            message.giftName === giftName
          ) {
            enqueueMessages([
              {
                type: constants.MESSAGE_TYPE_UPDATE,
                id: message.id,
                newValuesObj: { $add: { price, num } },
              },
            ]);
            return true;
          }
        }
        return false;
      },
      clearMessages() {
        flushSync(() => {
          setMessages([]);
          setPaidMessages([]);
        });
        smoothedMessageQueue.current = [];
        messagesBuffer.current = [];
        isSmoothed.current = true;
        lastSmoothChatMessageAddMs.current = null;
        chatRateMs.current = 1000;
        lastSmoothScrollUpdate.current = null;
        scrollTimeRemainingMs.current = scrollPixelsRemaining.current = 0;
        smoothScrollRafHandle.current = null;
        preinsertHeight.current = 0;
        maybeResizeScrollContainer();
        if (!atBottom.current) {
          scrollToBottom();
        }
      },
    }));

    useEffect(() => {
      scrollToBottom();
      window.addEventListener("resize", maybeResizeScrollContainer);
      return () => {
        window.removeEventListener("resize", maybeResizeScrollContainer);
        if (emitSmoothedMessageTimerId.current) {
          window.clearTimeout(emitSmoothedMessageTimerId.current);
        }
        resetSmoothScroll();
      };
    }, []);

    const onScroll = () => {
      refreshCantScrollStartTime();
      const scroller = scrollerRef.current;
      if (scroller) {
        atBottom.current =
          scroller.scrollHeight - scroller.scrollTop - scroller.clientHeight <
          SCROLLED_TO_BOTTOM_EPSILON;
      }
      flushMessagesBuffer();
    };

    return (
      <yt-live-chat-renderer
        class="style-scope yt-live-chat-app"
        className="style-scope yt-live-chat-app"
        style={{ "--scrollbar-width": "11px" } as React.CSSProperties}
        hide-timestamps=""
        onMouseMove={refreshCantScrollStartTime}
      >
        <Ticker
          messages={paidMessages}
          onUpdateMessages={setPaidMessages}
          showGiftName={showGiftName}
        />
        <yt-live-chat-item-list-renderer
          class="style-scope yt-live-chat-renderer"
          className="style-scope yt-live-chat-renderer"
          allow-scroll=""
        >
          <div
            ref={scrollerRef}
            id="item-scroller"
            className="style-scope yt-live-chat-item-list-renderer animated"
            onScroll={onScroll}
          >
            <div
              ref={itemOffsetRef}
              id="item-offset"
              className="style-scope yt-live-chat-item-list-renderer"
            >
              <div
                ref={itemsRef}
                id="items"
                className="style-scope yt-live-chat-item-list-renderer"
                style={{
                  overflow: "hidden",
                  transform: `translateY(${Math.floor(scrollPixelsRemaining.current)}px)`,
                }}
              >
                {messages.map((message) => {
                  if (message.type === constants.MESSAGE_TYPE_TEXT) {
                    return (
                      <TextMessage
                        key={message.id}
                        className="style-scope yt-live-chat-item-list-renderer"
                        time={message.time}
                        avatarUrl={message.avatarUrl}
                        authorName={message.authorName}
                        authorType={message.authorType}
                        privilegeType={message.privilegeType}
                        contentParts={constants.getShowContentParts(message)}
                        repeated={message.repeated}
                      />
                    );
                  } else if (message.type === constants.MESSAGE_TYPE_GIFT) {
                    return (
                      <PaidMessage
                        key={message.id}
                        className="style-scope yt-live-chat-item-list-renderer"
                        time={message.time}
                        avatarUrl={message.avatarUrl}
                        authorName={constants.getShowAuthorName(message)}
                        price={message.price}
                        priceText={
                          message.price <= 0 ? constants.getGiftShowNameAndNum(message) : ""
                        }
                        content={
                          message.price <= 0
                            ? ""
                            : constants.getGiftShowContent(message, showGiftName)
                        }
                      />
                    );
                  } else if (message.type === constants.MESSAGE_TYPE_MEMBER) {
                    return (
                      <MembershipItem
                        key={message.id}
                        className="style-scope yt-live-chat-item-list-renderer"
                        time={message.time}
                        avatarUrl={message.avatarUrl}
                        authorName={constants.getShowAuthorName(message)}
                        privilegeType={message.privilegeType}
                        title={message.title}
                      />
                    );
                  } else if (message.type === constants.MESSAGE_TYPE_SUPER_CHAT) {
                    return (
                      <PaidMessage
                        key={message.id}
                        className="style-scope yt-live-chat-item-list-renderer"
                        time={message.time}
                        avatarUrl={message.avatarUrl}
                        authorName={constants.getShowAuthorName(message)}
                        price={message.price}
                        content={constants.getShowContent(message)}
                      />
                    );
                  }
                  return null;
                })}
              </div>
            </div>
          </div>
        </yt-live-chat-item-list-renderer>
      </yt-live-chat-renderer>
    );
  }
);
